### ISSUE TITLE
An issue : fail to generate abstract syntax trees in the preprocessing stage

### ISSUE THREAD

**Issue by 1789120321** [WSP-LAB/Montage#5]
Hi, When I use my machine to run the montage to preprocess the dataset, I have some problems and hope to get your help, Thx!

First, There are many errors written in the log files in the `data\log` directory. The error messages are as follows:

```

============== STDOUT ===============

============== STDERR ===============
Couldn't load file '/home/ubuntu20/Desktop/III/Montage-master/js-test-suite/testsuite/fcfbc86708bc3a4062c2091a062e13b6.js'
Couldn't load file '/home/ubuntu20/Desktop/III/Montage-master/js-test-suite/testsuite/45e1d6de6cbdd6f2ea33d472d566096a.js'
ReferenceError: 'inSection' is not defined
   at Global code (/home/ubuntu20/Desktop/III/Montage-master/data/0a3f6ac9816b3199997b5571888c823a.js:36:1)

MONTAGE_RETURN: 0
```

Then, in terminal, the error messages are as follows :

```
ubuntu20@ubuntu:~/Desktop/III/Montage-master/src$ python3 main.py --opt preprocess --config /home/ubuntu20/Desktop/III/Montage-master/conf/conf.json
[1/8] Filtering out JS with errors
[INFO] Start executing 299 JS files
[2/8] Parsing JS code into ASTs
[INFO] Start parsing 60 JS files
[3/8] Stripping args of eval func calls
[4/8] Normalizing identifiers
[5/8] Fragmentizing JS ASTs
[6/8] Aggregating fragments
[7/8] Replacing uncommon fragments
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 53, in main
    exec_preprocess(conf)
  File "main.py", line 25, in exec_preprocess
    preprocessor.preprocess()
  File "/home/ubuntu20/Desktop/III/Montage-master/src/preprocess/preprocess.py", line 77, in preprocess
    self.mark_oov()
  File "/home/ubuntu20/Desktop/III/Montage-master/src/preprocess/preprocess.py", line 49, in mark_oov
    renewed_data = oov.replace_uncommon(self._seed_dict,
  File "/home/ubuntu20/Desktop/III/Montage-master/src/preprocess/oov.py", line 42, in replace_uncommon
    ret = collect_oov(seed_dict, frag_list)
  File "/home/ubuntu20/Desktop/III/Montage-master/src/preprocess/oov.py", line 12, in collect_oov
    sorted_frags, oov_idx = sort_frags(seed_dict)
  File "/home/ubuntu20/Desktop/III/Montage-master/src/preprocess/oov.py", line 74, in sort_frags
    sorted_frags, frq = zip(*frag_frq)
ValueError: not enough values to unpack (expected 2, got 0)
```

And, I tried to enter the directory  `data\ast`. I found that the folder is empty. In other words, the program did not generate an abstract syntax tree. 

I do not know how to solve the problems, so I hope to get your help. Thx!

**Environment**
Ubuntu 20.04.1 LTS
chakra version：https://github.com/microsoft/ChakraCore

**Comment by leeswimming** [comment]
It seems you are only using 299 JS files instead of the entire seed files provided at this [repository](https://github.com/WSP-LAB/js-test-suite). The harness files should exist in the same directory. Please put all seed files in the designated `seed_dir`.
